#!/bin/bash

dps=$(nslookup $1 101.0.101.101 | awk 'NR==5' | awk '{print $2}')
dpr=$(nslookup $1 101.0.101.106 | awk 'NR==5' | awk '{print $2}')
crus=$(nslookup $1 111.118.163.5 | awk 'NR==5' | awk '{print $2}')
crur=$(nslookup $1 111.118.165.83 | awk 'NR==5' | awk '{print $2}')
crum=$(nslookup $1 182.160.136.154 | awk 'NR==5' | awk '{print $2}')

echo -e "\nChecking Nameservers for domain location\n"
echo "DP Shared       : $dps"
echo "DP Reseller     : $dpr"
echo "Crucial Shared  : $crus"
echo "Crucial Resell  : $crur"
echo "Crucial Managed : $crum"
echo ""

if [ ! -z $dps ]; then host $dps | awk '{print $5}'; fi
if [ ! -z $dpr ]; then host $dpr | awk '{print $5}'; fi
if [ ! -z $crus ]; then host $crus | awk '{print $5}'; fi
if [ ! -z $crur ]; then host $crur | awk '{print $5}'; fi
if [ ! -z $crum ]; then host $crum | awk '{print $5}'; fi
echo ""
