#!/bin/bash

if [ $# != 1 ]; then
echo “Please insert an IP Address”
exit 1
fi

ip=$1

iptables -I INPUT -p tcp -s $ip --dport 139 -j ACCEPT
iptables -I INPUT -p tcp -s $ip --dport 445 -j ACCEPT
iptables -I INPUT -p udp -s $ip --dport 137 -j ACCEPT
iptables -I INPUT -p udp -s $ip --dport 138 -j ACCEPT

iptables -I INPUT -p tcp -s 0.0.0.0/0 --dport 139 -j DROP
iptables -I INPUT -p tcp -s 0.0.0.0/0 --dport 445 -j DROP
iptables -I INPUT -p udp -s 0.0.0.0/0 --dport 137 -j DROP
iptables -I INPUT -p udp -s 0.0.0.0/0 --dport 138 -j DROP
