#!/bin/bash

server=$1

echo -e "\nChecking SSL Details\n"

curl --insecure -v https://$server 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'
ssl=$(curl --insecure -v https://$server 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'|wc -l)

if [ $ssl = 0 ]; then echo "Valid SSL Certificate not found on this domain" 
else echo | openssl s_client -servername $server -connect $server:443 2>/dev/null | openssl x509 -text 2>/dev/null | grep DNS ;fi
echo ""

