#!/usr/bin/python3

import whois
import argparse
import sys


def input_parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('-t', '--target',
                        help='Enter domain name for whois lookup')

    if len(sys.argv) == 1:
        parser.print_help()
        exit()

    return parser.parse_args()


def whois_lookup():
    try:
        w = whois.whois(domain)
        return w
    except:
        return False


if __name__ == '__main__':

#    arg = input_parse()
#    domain = arg.target

    if len(sys.argv) > 2:
        print('Usage: %s domain' % sys.argv[0])
        exit()
    try:
        domain = sys.argv[1]
        domain_lookup = whois_lookup()
        print(domain_lookup)
    except:
        print('Usage: %s domain' % sys.argv[0])
        exit()
